name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    # Memberi izin ke GitHub Action untuk membuat "Release"
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Create Android Platform Folder
      working-directory: ./mobile
      run: |
        flutter config --enable-android
        flutter create --platforms=android .

    - name: Get Dependencies
      working-directory: ./mobile
      run: flutter pub get

    - name: Build APK
      working-directory: ./mobile
      run: flutter build apk --release

    - name: Rename APK
      run: mv mobile/build/app/outputs/flutter-apk/app-release.apk TokoKas-Release.apk

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: TokoKas-Release.apk
        tag_name: "v1.0.0"
        name: "TokoKas v1.0.0 (APK)"
        body: "Ini adalah rilis pertama aplikasi KasirSantri/TokoKas untuk platform Android. \n\n🚀 **Silakan klik file `TokoKas-Release.apk` di bagian Assets di bawah ini untuk men-download dan menginstalnya di HP Anda!**"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
