name: Build Android APK

on:
  # Akan otomatis berjalan setiap kali Anda melakukan git push ke GitHub
  push:
    branches:
      - main
    paths:
      - 'mobile/**'
  # Tetap bisa dijalankan manual jika dibutuhkan
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Create Android Platform Folder
      working-directory: ./mobile
      run: |
        flutter config --enable-android
        flutter create --platforms=android .

    - name: Get Dependencies
      working-directory: ./mobile
      run: flutter pub get

    - name: Build APK
      working-directory: ./mobile
      run: flutter build apk --release

    - name: Rename APK
      run: mv mobile/build/app/outputs/flutter-apk/app-release.apk TokoKas-Latest.apk

    - name: Update Latest Release
      uses: softprops/action-gh-release@v1
      with:
        files: TokoKas-Latest.apk
        tag_name: "latest"
        name: "TokoKas (Versi Terbaru)"
        body: "APK ini akan selalu diperbarui secara otomatis setiap kali ada perubahan kode. \n\n🚀 **Silakan klik file `TokoKas-Latest.apk` di bawah ini untuk men-download versi terbarunya!**"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
